//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/message_type.proto
namespace proto.message_type
{
    [global::ProtoBuf.ProtoContract(Name=@"EMessageType")]
    public enum EMessageType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENone", Value=0)]
      ENone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESCFrameInit", Value=100)]
      ESCFrameInit = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ECSFrame", Value=101)]
      ECSFrame = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESCFrame", Value=102)]
      ESCFrame = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ECSLogin", Value=10001)]
      ECSLogin = 10001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESCLogin", Value=10002)]
      ESCLogin = 10002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ECSReady", Value=11001)]
      ECSReady = 11001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESCReady", Value=11002)]
      ESCReady = 11002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESCSight", Value=20001)]
      ESCSight = 20001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EMax", Value=999999)]
      EMax = 999999
    }
  
}