#ifndef __NET_DEFINED_HPP__
#define __NET_DEFINED_HPP__

#ifndef BUFFER_SIZE
#define BUFFER_SIZE 10240
#endif // BUFFER_SIZE

#ifndef MSG_BUFFER_SIZE
#define MSG_BUFFER_SIZE (BUFFER_SIZE*10)
#endif // MSG_BUFFER_SIZE

#ifndef CELL_THREAD_COUNT
#define CELL_THREAD_COUNT 6
#endif // CELL_THREAD_COUNT

#endif // __NET_DEFINED_HPP__