//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/player.proto
namespace proto.player
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSLogin")]
  public partial class CSLogin : global::ProtoBuf.IExtensible
  {
    public CSLogin() {}
    

    private string _UserName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"UserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string UserName
    {
      get { return _UserName; }
      set { _UserName = value; }
    }

    private string _PassWord = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"PassWord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PassWord
    {
      get { return _PassWord; }
      set { _PassWord = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCLogin")]
  public partial class SCLogin : global::ProtoBuf.IExtensible
  {
    public SCLogin() {}
    

    private bool _Ret = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Ret", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Ret
    {
      get { return _Ret; }
      set { _Ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}